🔗 :: (104) 후기 재구현
Team-return/JOBIS-ANDROID-V2 pull request #105
Opened 2024-03-07 10:07 UTC by rladmsdh

## 개요

### 작업 내용
- 후기 기획이 바뀐것을 재구현 합니다

### 할 말
> 없음

2024-03-07 23:41 UTC, Tmdhoon2 requested changes

2024-03-07 23:41 UTC, Tmdhoon2 commented on feature/review/src/main/java/team/retum/review/viewmodel/ReviewViewModel.kt
>              postReviewUseCase.invoke(
함수 이름 invoke인 애들은 함수 접근 안하고 클래스 이름만으로 바로 사용할 수 있어용

2024-03-07 23:49 UTC, rladmsdh commented on feature/review/src/main/java/team/retum/review/ui/PostReviewScreen.kt
> +                    enabled = false,
이거 원래 버튼 안눌리는걸로 되어있던데

2024-03-08 02:29 UTC, Tmdhoon2 approved these changes

2024-03-08 04:09 UTC, rladmsdh commented on feature/review/src/main/java/team/retum/review/ui/PostReviewScreen.kt
> +    var checked by remember { mutableStateOf("") }
이런 변수들이 viewModel로 가기도 하는데 그게 꼭 의무는 아니고 이런식으로 뷰의 상태를 관리하는 변수들은 따로 빼지 않고 뷰에 직접 선언하기도 해 이걸 뷰모델로 빼면 로직이 복잡해져서 그냥 뷰 함수에 선언했어
위에 질문도 마찬가지

2024-03-08 04:14 UTC, parkuiery approved these changes

2024-03-08 04:15 UTC, merged