🔗 :: (#115) 공지사항 상세 기능 구현
Team-return/JOBIS-ANDROID-V2 pull request #122
Opened 2024-03-10 13:35 UTC by parkuiery

## 개요

공지사항 상세를 기능 개발합니다.

### 작업 내용
- 

### 할 말
> 스크린 아직 안나와서 이상할 수도 있어요

2024-03-10 13:58 UTC, rladmsdh approved these changes

2024-03-11 06:53 UTC, Tmdhoon2 requested changes

2024-03-11 06:53 UTC, Tmdhoon2 commented on feature/notice/src/main/java/team/retum/jobis/notice/navigation/NoticeDetailsNavigation.kt
> +const val NOTICE_ID = "notice-id"
이거 카멜케이스로 맞추는 암묵적인 룰이 있어요

2024-03-11 07:32 UTC, parkuiery commented on feature/notice/src/main/java/team/retum/jobis/notice/navigation/NoticeDetailsNavigation.kt
> +const val NOTICE_ID = "notice-id"
그럼 어떻게 바꿔요?
근데 이거 resourceKey에서 받아와야해요?

2024-03-11 13:03 UTC, Tmdhoon2 approved these changes

2024-03-11 13:04 UTC, merged