🔗 :: (#135) 공지사항 상세 네비게이션 수정
Team-return/JOBIS-ANDROID-V2 pull request #139
Opened 2024-03-12 14:39 UTC by parkuiery

## 개요

공지사항 상세 네비게이션을 수정합니다

### 작업 내용
- 

### 할 말
> 없음

2024-03-12 22:30 UTC, Tmdhoon2 requested changes

2024-03-12 22:30 UTC, Tmdhoon2 commented on feature/notice/src/main/java/team/retum/jobis/notice/viewmodel/NoticeDetailsViewModel.kt
> +                    postSideEffect(NoticeDetailsSideEffect.BadRequest)
이 부분은 스크린쪽에서 예외처리가 안되고 있는것 같아요

2024-03-12 23:32 UTC, Tmdhoon2 requested changes

2024-03-12 23:32 UTC, Tmdhoon2 commented on feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticeDetailsScreen.kt
> +                    )
.show() 호출해야해용

2024-03-13 02:12 UTC, Tmdhoon2 approved these changes

2024-03-13 02:41 UTC, diddbsgh approved these changes

2024-03-13 03:28 UTC, merged