🔗 ::  (#164) 면접후기 작성 안 해도 넘어가지는 버그
Team-return/JOBIS-ANDROID-V2 pull request #172
Opened 2024-03-19 10:06 UTC by parkuiery

## 개요

면접후기 작성을 안해도 넘어가지는 버그 수정
### 작업 내용
- 

### 할 말
> 없음

2024-03-19 10:10 UTC, diddbsgh approved these changes

2024-03-19 22:25 UTC, Tmdhoon2 requested changes

2024-03-19 22:25 UTC, Tmdhoon2 commented on feature/review/src/main/java/team/retum/review/viewmodel/PostReviewViewModel.kt
> +                }
if안에 있는 조건문을 buttonEnabled 안에 넣으면 코드가 더 깔끔해질 것 같아요

2024-03-19 22:25 UTC, Tmdhoon2 commented on feature/review/src/main/java/team/retum/review/viewmodel/PostReviewViewModel.kt
> +                    setState { state.value.copy(buttonEnabled = false) }
여기도 마찬가지로 state.value.copy(buttonEnabled == state.value.checked.isNotEmpty()) 이런식으로 하면 코드 더 줄일 수 있을 것 같습니당

2024-03-20 01:35 UTC, Tmdhoon2 approved these changes

2024-03-20 01:41 UTC, merged