🔗 :: (#166) 공지사항 상세 다운로드 기능 구현
Team-return/JOBIS-ANDROID-V2 pull request #227
Opened 2024-04-07 07:05 UTC by parkuiery

## 개요

### 작업 내용
- 공지사항 상세 페이지의 파일 다운로드 구현

### 할 말
> 없음

2024-04-08 02:11 UTC, rladmsdh commented on feature/notice/src/main/java/team/retum/jobis/notice/viewmodel/NoticeDetailsViewModel.kt
> +        GlobalScope.launch(Dispatchers.IO) {
GlobalScope를 쓴 이유가 있을까요?

2024-04-08 02:29 UTC, Tmdhoon2 requested changes

2024-04-08 02:29 UTC, Tmdhoon2 commented on feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticeDetailsScreen.kt
> +    saveFileData: (urlSting: String, fileName: String, context: Context) -> Unit,
타입만 보고 알 수 있는 변수들은 굳이 이름을 명시하지 않아도 될 것 같아요

2024-04-08 02:29 UTC, Tmdhoon2 commented on feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticeDetailsScreen.kt
> +
불필요한 공백이 있어요

2024-04-08 02:29 UTC, Tmdhoon2 commented on feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticeDetailsScreen.kt
> +    val context = LocalContext.current
이거 상위 컴포저블 함수로 옮기면 람다에 context 제거할 수 있을 것 같아요

2024-04-08 02:29 UTC, Tmdhoon2 commented on feature/notice/src/main/java/team/retum/jobis/notice/viewmodel/NoticeDetailsViewModel.kt
> +                Log.d("ERROR", e.toString())
로그 필요한가요??

2024-04-08 07:10 UTC, parkuiery commented on feature/notice/src/main/java/team/retum/jobis/notice/viewmodel/NoticeDetailsViewModel.kt
> +        GlobalScope.launch(Dispatchers.IO) {
백그라운드 처리와 다운로드 기능이라 전역으로 해야할거 같아서 작성했는데 찾아보니까 위험 요소가 많아 viewModelScope로 수정했습니다

2024-04-11 05:46 UTC, rladmsdh approved these changes

2024-04-11 05:56 UTC, Tmdhoon2 requested changes

2024-04-14 00:06 UTC, Tmdhoon2 commented
토스트 추가 작업이 진행중인걸로 알고 있어서 우선 draft pr로 바꿔둘게용

2024-04-24 08:04 UTC, Tmdhoon2 commented on feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticeDetailsScreen.kt
> +                        message = context.getString(R.string.success_download),
다운로드 성공했을때만 popup 뜨는거면 xml 파일 안에서 메세지랑 버튼 텍스트 고정시켜두는게 낫지 않을까요??

2024-04-24 08:07 UTC, Tmdhoon2 commented on feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticeDetailsScreen.kt
> +}
얘네는 notice 모듈 안에 util 패키지 만들어서 파일로 따로 빼는게 좋을 것 같아요

2024-04-24 08:08 UTC, Tmdhoon2 commented on feature/notice/src/main/java/team/retum/jobis/notice/viewmodel/NoticeDetailsViewModel.kt
> +    internal fun saveFileData(urlString: String, destinationPath: String, context: Context) {
함수 파라미터 컨벤션 지켜주세요

2024-04-24 08:09 UTC, Tmdhoon2 commented on feature/notice/src/main/java/team/retum/jobis/notice/viewmodel/NoticeDetailsViewModel.kt
> +                input.close()
꼭 반영하실 필요는 없는데 이렇게 조금 복잡한 로직들은 작업할 당시에 주석 달아놓으면 나중에 유지보수하기 편할 것 같다고 생각합니당

2024-04-24 08:14 UTC, Tmdhoon2 commented on feature/notice/src/main/res/values/string.xml
> +    <string name="failed_download">다운로드를 실패했습니다</string>
다운로드에 실패했습니다 가 조금 더 자연스러운 것 같아용

2024-04-24 08:15 UTC, Tmdhoon2 commented
혹시 fadeIn/Out 애니메이션 적용 가능한가요??

2024-04-24 09:20 UTC, parkuiery commented on feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticeDetailsScreen.kt
> +                        message = context.getString(R.string.success_download),
나중에 popup쓸일 있으면 쓸려고 비워둔거긴 한데 고정시킬까요?

2024-04-24 11:27 UTC, Tmdhoon2 commented on feature/notice/src/main/java/team/retum/jobis/notice/ui/NoticeDetailsScreen.kt
> +                        message = context.getString(R.string.success_download),
아 그러면 그냥 두는게 좋을것 같아용

2024-04-24 12:34 UTC, Tmdhoon2 approved these changes

2024-04-24 12:52 UTC, merged