🔗 :: (#21) 이메일 입력 스크린 퍼블리싱
Team-return/JOBIS-ANDROID-V2 pull request #23
Opened 2024-01-26 10:01 UTC by parkuiery

## 개요
<img width="337" alt="image" src="https://github.com/Team-return/JOBIS-ANDROID-V2/assets/128464859/7ed418cd-431c-434c-90a9-37c287a68e86">

이메일 입력 스크린을 퍼블리싱 했습니다.

### 작업 내용
- InputEmailScreen 퍼블리싱
- InputEmailNavigation 구현

### 할 말
> 없음

2024-01-26 12:39 UTC, Tmdhoon2 requested changes

2024-01-26 12:39 UTC, Tmdhoon2 commented on feature/signup/src/main/java/team/retum/signup/ui/InputEmailScreen.kt
> +    var authenticationCode by remember { mutableStateOf("") }
여기 viewmodel로 나중에 옮기게 될 것 같은데 todo 하나만 달아주세용

2024-01-26 12:39 UTC, Tmdhoon2 commented on feature/signup/src/main/res/values/strings.xml
> +    <string name="hint_authentication_code">이메일로 온 코드 입력해주세요</string>
여기 코드"를" 빠진 것 같아요

2024-01-26 12:50 UTC, parkuiery commented on app/src/main/java/team/retum/jobisandroidv2/navigation/AuthNavigation.kt
> +            onEmailClick = navController::navigateToInputEmail,
수정했습니다

2024-01-26 12:50 UTC, parkuiery commented on feature/signup/src/main/java/team/retum/signup/ui/InputEmailScreen.kt
> +    var authenticationCode by remember { mutableStateOf("") }
수정했습니다

2024-01-26 12:50 UTC, parkuiery commented on feature/signup/src/main/res/values/strings.xml
> +    <string name="hint_authentication_code">이메일로 온 코드 입력해주세요</string>
수정했습니다

2024-01-26 21:32 UTC, Tmdhoon2 approved these changes

2024-01-28 10:37 UTC, diddbsgh approved these changes

2024-01-29 04:46 UTC, merged