🔗 :: (#237) 랜딩 페이지 개선
Team-return/JOBIS-ANDROID-V2 pull request #238
Opened 2024-04-13 13:31 UTC by rladmsdh

## 개요

### 작업 내용
- 랜딩페이지 변경

### 할 말
> 없음

2024-04-13 14:19 UTC, parkuiery approved these changes

2024-04-13 14:19 UTC, parkuiery commented on feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/component/RecruitmentItems.kt
> +            var bookmarked = recruitment.bookmarked
이렇게 처리하는게 더 효율적인가요?

2024-04-14 00:04 UTC, Tmdhoon2 requested changes

2024-04-14 00:04 UTC, Tmdhoon2 commented on feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/component/RecruitmentItems.kt
> +            var bookmarked = recruitment.bookmarked
변경하신 이유가 뭔가용

2024-04-14 00:44 UTC, Tmdhoon2 approved these changes

2024-04-14 01:09 UTC, rladmsdh commented on feature/recruitment/src/main/java/team/retum/jobis/recruitment/ui/component/RecruitmentItems.kt
> +            var bookmarked = recruitment.bookmarked
원래 방식에 오류가 있어서 수정했습니다

2024-04-14 01:09 UTC, merged