🔗 :: (#243) R8 적용
Team-return/JOBIS-ANDROID-V2 pull request #244
Opened 2024-04-16 14:50 UTC by rladmsdh

## 개요

<img width="1106" alt="Screenshot 2024-04-16 at 11 48 06 PM" src="https://github.com/Team-return/JOBIS-ANDROID-V2/assets/103027173/c6f558cc-1bb4-4b54-8dcf-a748280153d5">
개선한것
<img width="1174" alt="Screenshot 2024-04-16 at 10 25 50 AM" src="https://github.com/Team-return/JOBIS-ANDROID-V2/assets/103027173/5b5c89ca-54d2-42ce-96be-e19ae0031420">
기존

### 작업 내용
- R8적용 -> .dex파일을 25개에서 2개로 줄임

### 할 말
> 찐찐찐찐막 Pr 이제 진짜 안함
> 내 허락 받기 전까진 proguard파일 절대 수정 금지!
> 오류 있을수도 있으니까 실행 많이 시켜보고 테스트 해보셔요

2024-04-16 22:46 UTC, parkuiery commented
작동 방식에 대해 설명해주세요

2024-04-16 22:48 UTC, Tmdhoon2 commented
사진 상으로는 앱 전체 크기가 안 보이는것 같은데 어떻게 개선됐나요??

2024-04-16 22:51 UTC, Tmdhoon2 requested changes

2024-04-16 22:51 UTC, Tmdhoon2 commented on app/proguard-rules.pro
주석 설명중에 중복되는 내용이 많은거 같은데 최상단에 한 번만 쓰고 나머지는 지우는게 좋을 것 같습니다

2024-04-16 23:46 UTC, rladmsdh commented
제가 공부하면서 정리해둔 파일이 있는데 참고하시면 아마 코멘트에 대한 답이 될것 같습니다
https://acidic-olivine-887.notion.site/34eacf888c8b45d19ce54352bc9eb123?pvs=4

2024-04-17 07:20 UTC, Tmdhoon2 approved these changes

2024-04-17 22:43 UTC, parkuiery approved these changes

2024-04-18 01:36 UTC, merged