🔗 :: (#261) 데이터 포멧 코드 개선
Team-return/JOBIS-ANDROID-V2 pull request #262
Opened 2024-05-12 12:11 UTC by rladmsdh

## 개요

<img width="845" alt="Screenshot 2024-05-12 at 9 09 42 PM" src="https://github.com/Team-return/JOBIS-ANDROID-V2/assets/103027173/8b69af19-816d-40d0-acae-dfb3fefc0b8e">

### 작업 내용
- 데이터 포멧 개선

### 할 말
> Retrofit과 같이 사용했을 때 메모리 버퍼를 재사용하여 메모리 할당 및 해제에 드는 오버헤드를 줄여주고 있다고 합니다

2024-05-12 14:14 UTC, parkuiery approved these changes

2024-05-12 14:14 UTC, parkuiery commented on core/network/src/main/java/team/retum/network/model/request/PostReviewRequest.kt
> +@JsonClass(generateAdapter = true)
이거 추가 안하면 어떻게 되나요?

2024-05-12 14:20 UTC, Tmdhoon2 requested changes

2024-05-12 14:20 UTC, Tmdhoon2 commented on core/network/build.gradle.kts
>      implementation(libs.squareup.retrofit.converter.gson)
기존 의존성은 나중에 제거하실 계획인가요??

2024-05-12 14:20 UTC, Tmdhoon2 commented on core/network/src/main/java/team/retum/network/model/request/file/CreatePresignedUrlRequest.kt
>  ) {
내부 클래스에는 @JsonClass 어노테이션을 명시하지 않아도 될까요?

2024-05-12 14:26 UTC, rladmsdh commented on core/network/build.gradle.kts
>      implementation(libs.squareup.retrofit.converter.gson)
까먹었네요 수정하겠습니다

2024-05-12 14:38 UTC, rladmsdh commented on core/network/src/main/java/team/retum/network/model/request/PostReviewRequest.kt
> +@JsonClass(generateAdapter = true)
직렬화 성능을 높이도록 하는 코드라 추가했습니다

2024-05-12 14:42 UTC, rladmsdh commented on core/network/src/main/java/team/retum/network/model/request/file/CreatePresignedUrlRequest.kt
>  ) {
명시해야되네요

2024-05-13 01:05 UTC, Tmdhoon2 approved these changes

2024-05-13 01:06 UTC, merged