🔗 :: (#263) UI draw 속도 개선
Team-return/JOBIS-ANDROID-V2 pull request #264
Opened 2024-05-13 14:27 UTC by rladmsdh

## 개요

뷰가 그려지기 전에 있는 딜레이를 감소시킨다

### 작업 내용
- 리스트 컴포지션 개선
- 중복해서 그리는 뷰 감소

### 할 말
> 없음

2024-05-13 14:44 UTC, Tmdhoon2 requested changes

2024-05-13 14:44 UTC, Tmdhoon2 commented on feature/company/src/main/java/team/retum/company/component/CompanyItems.kt
> +        items(
itemIndexed -> item으로 변경하신 이유가 있나요?

2024-05-13 23:37 UTC, rladmsdh commented on feature/company/src/main/java/team/retum/company/component/CompanyItems.kt
> +        items(
items가 itemIndexed보다 내부 구현이 간결하다 보니 item이 필요 없을것 같아서 변경했습니다.

2024-05-13 23:44 UTC, Tmdhoon2 requested changes

2024-05-13 23:44 UTC, Tmdhoon2 commented on feature/company/src/main/java/team/retum/company/component/CompanyItems.kt
> +        items(
it이 조금 구별이 안 갈 수 있을 것 같습니다. index라는걸 명시해주면 좋을 것 같아요

2024-05-14 00:25 UTC, Tmdhoon2 approved these changes

2024-05-14 02:14 UTC, parkuiery approved these changes

2024-05-14 02:40 UTC, merged