🔗 :: (#24) 비밀번호 설정 스크린 퍼블리싱
Team-return/JOBIS-ANDROID-V2 pull request #27
Opened 2024-01-30 13:35 UTC by diddbsgh

## 개요
<img width="288" alt="비밀번호 설정" src="https://github.com/Team-return/JOBIS-ANDROID-V2/assets/128462405/6e605afe-ecb2-46d0-8811-8039aa69b143">

비밀번호 설정 스크린을 퍼블리싱했습니다.

### 작업 내용
- SettingPasswordScreen 퍼블리싱
- SettingPasswordNavigation 구현

### 할 말
> 없음

2024-01-30 13:59 UTC, parkuiery commented on feature/signup/src/main/java/team/retum/signup/ui/SettingPasswordScreen.kt
> +    var checkPassword by remember { mutableStateOf("") }
나중에 viewModel로 옮길수 있게 TODO 해주세요

2024-01-31 01:49 UTC, Tmdhoon2 requested changes

2024-01-31 01:49 UTC, Tmdhoon2 commented on app/src/main/java/team/retum/jobisandroidv2/navigation/AuthNavigation.kt
> +
여기 필요없는 개행 한 줄 지워주세요

2024-01-31 01:49 UTC, Tmdhoon2 commented on app/src/main/java/team/retum/jobisandroidv2/navigation/AuthNavigation.kt
> +            navController = navController,
이거 navController 자체를 넘겨주는 방식 말고 밑에 onBackClick이나 onNextClick 처럼 람다식을 넘겨주는 방식으로 바꿔주세용

2024-01-31 01:49 UTC, Tmdhoon2 commented on feature/signup/src/main/java/team/retum/signup/ui/SettingPasswordScreen.kt
> +        descriptionType = DescriptionType.Information
여기 맨 마지막줄에 콤마 붙여주시고 소괄호 한 칸 밀려있는거 같아요

2024-01-31 01:49 UTC, Tmdhoon2 commented on feature/signup/src/main/java/team/retum/signup/ui/SettingPasswordScreen.kt
> +
여기도 필요없는 개행 제거해주세요

2024-01-31 01:49 UTC, Tmdhoon2 commented on feature/signup/src/main/java/team/retum/signup/ui/InputEmailScreen.kt
> +                      navController.navigate(route = NAVIGATION_SIGN_UP_SETTING_PASSWORD)
여기도 좀 더 밀려있는거 같아용

2024-01-31 01:49 UTC, Tmdhoon2 commented on feature/signup/src/main/java/team/retum/signup/navigation/InputEmailScreen.kt
> +        InputEmailScreen(navController = navController, onBackClick = onBackClick)
한 줄인 경우
- named argument (ex navController = navController)
두 줄 이상인 경우
- name argument
- trailing comma (마지막줄에 콤마 붙이는거)

2024-01-31 14:42 UTC, Tmdhoon2 submitted a review, later dismissed

2024-01-31 15:34 UTC, rladmsdh commented on feature/signup/src/main/java/team/retum/signup/navigation/SettingPasswordScreen.kt
> +){
여기 띄어쓰기

2024-01-31 15:34 UTC, rladmsdh commented on feature/signup/src/main/java/team/retum/signup/ui/SettingPasswordScreen.kt
> +import androidx.compose.foundation.Image
안쓰는 import 지우기

2024-01-31 15:34 UTC, rladmsdh commented on feature/signup/src/main/java/team/retum/signup/ui/SettingPasswordScreen.kt
> +            modifier = Modifier.padding(bottom = 24.dp),
이거 디자인이랑 안맞아
bottom = 24.dp가 아니라 vertical = 12.dp야

2024-01-31 15:34 UTC, rladmsdh commented on app/src/main/java/team/retum/jobisandroidv2/navigation/AuthNavigation.kt
>  import team.retum.landing.landing
여기 안쓰는 import 지워줘

2024-01-31 15:41 UTC, rladmsdh commented on feature/signup/src/main/java/team/retum/signup/ui/SettingPasswordScreen.kt
> +            onCheckPassword = { password = it },
여기 잘못되어있는데 viewModel 추가하면 바꿔줘

2024-02-02 11:58 UTC, Tmdhoon2 approved these changes

2024-02-02 12:01 UTC, rladmsdh approved these changes

2024-02-02 13:19 UTC, merged