🔗 :: (#272) 테스트 코드 개선
Team-return/JOBIS-ANDROID-V2 pull request #274
Opened 2024-07-04 02:21 UTC by rladmsdh

## 개요

### 작업 내용
- 디자인시스템 그래들에 오류를 수정했습니다.
- 회사 뷰모델에 기본적인 테스트코드를 추가했습니다.

### 할 말
> 제대로 테스트를 하려고 짠 코드라기보단 2학년이 뷰모델 테스트코드를 처음부터 짜려면 어려워할수도 있어서 참고할만한 코드예시 남긴다.

2024-07-04 06:17 UTC, parkuiery commented on feature/company/src/androidTest/java/team/retum/company/CompanyViewModelTest.kt
> +        val newName = "홍승재 타이어"
테스트 코드에서는 원래 이런식으로 더미 데이터 값을 넣나요?

2024-07-04 06:22 UTC, parkuiery commented on feature/company/src/androidTest/java/team/retum/company/CompanyViewModelTest.kt
> +        assertEquals(newName, viewModel.state.value.name)
테스트가 실패하면 newName이 나오는건가요?

2024-07-04 06:29 UTC, rladmsdh commented on feature/company/src/androidTest/java/team/retum/company/CompanyViewModelTest.kt
> +        val newName = "홍승재 타이어"
아니긴 한데 나름 유의미한 값이라고 생각해서 그렇게 해봤고
다른 테스트해보고싶은 값이 있으면 그때 또 추가하면 됩니당

2024-07-04 12:47 UTC, rladmsdh commented on feature/company/src/androidTest/java/team/retum/company/CompanyViewModelTest.kt
> +        assertEquals(newName, viewModel.state.value.name)
테스트가 실패하면 그냥 실패했다고 나오고 딱히 실패에 대한 코드는 작성을 안했습니다.
경우에 따라 다르겠지만 보통 유효값안에서 검증을 진행해서 애초에 테스트가 실패하면 그냥 코드가 잘못된 경우가 많아요

2024-07-04 13:32 UTC, Tmdhoon2 requested changes

2024-07-04 14:18 UTC, rladmsdh commented on core/design-system/build.gradle.kts
> +    }
그냥 minSdk만 제거해도 될것 같습니다

2024-07-04 22:24 UTC, Tmdhoon2 commented on core/design-system/build.gradle.kts
> +    }
그렇네요 testInstrumentationRunner만 두면 될 것 같습니당

2024-07-04 22:26 UTC, Tmdhoon2 requested changes

2024-07-04 22:26 UTC, Tmdhoon2 commented on feature/company/build.gradle.kts
이거 의존성 추가 안해도 작동했었던것 같은데 한 번 더 확인해주실 수 있나요??

2024-07-05 00:01 UTC, parkuiery approved these changes

2024-07-05 01:57 UTC, Tmdhoon2 approved these changes

2024-07-05 02:03 UTC, merged