🔗 :: (#38) 북마크 스크린 퍼블리싱
Team-return/JOBIS-ANDROID-V2 pull request #53
Opened 2024-02-07 15:40 UTC by rladmsdh

## 개요

<img width="270" alt="Screenshot 2024-02-08 at 12 37 15 AM" src="https://github.com/Team-return/JOBIS-ANDROID-V2/assets/103027173/c03cf6b4-f45d-4cb5-9e80-f3867f2eeec4">
<img width="270" alt="Screenshot 2024-02-08 at 12 39 20 AM" src="https://github.com/Team-return/JOBIS-ANDROID-V2/assets/103027173/5aa3cbd7-3595-44d6-bc00-da1dbda31bf5">

### 작업 내용
- 북마크 페이지 퍼블리싱

### 할 말
> 없음

2024-02-07 16:16 UTC, Tmdhoon2 requested changes

2024-02-07 16:16 UTC, Tmdhoon2 commented on feature/bookmark/src/main/java/team/retum/bookmark/ui/BookmarkScreen.kt
> +                bookmarkList.forEach {
여기는 LazyColumn 사용할 수 있을 것 같습니당

2024-02-07 16:16 UTC, Tmdhoon2 commented on feature/bookmark/src/test/java/team/retum/bookmark/ExampleUnitTest.kt
> +import org.junit.Assert.*
와일드 카드 import 제거해주세용

2024-02-07 16:16 UTC, rladmsdh commented on app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
> +            }
맞네요 고칠게요

2024-02-08 01:55 UTC, Tmdhoon2 approved these changes

2024-02-08 04:58 UTC, parkuiery approved these changes

2024-02-08 05:50 UTC, merged