🔗 :: (#39) 버그 제보 스크린 퍼블리싱
Team-return/JOBIS-ANDROID-V2 pull request #59
Opened 2024-02-12 10:32 UTC by Tmdhoon2

## 개요

<img width = "200" src = "https://github.com/Team-return/JOBIS-ANDROID-V2/assets/102812085/7762c2a5-fb88-4bdd-9e48-f409761584e8"/>
<img width = "200" src = "https://github.com/Team-return/JOBIS-ANDROID-V2/assets/102812085/ab045eed-d5b0-4e8e-a39d-14760e01af2a"/>

버그 제보 스크린을 퍼블리싱 했습니다.

### 작업 내용
- DevelopmentArea enum 추가
- ReportBugScreen 추가
- ReportBugNavigation 추가

### 할 말
> 없음

2024-02-12 14:12 UTC, rladmsdh commented on feature/bug/src/main/java/team/retum/bug/ReportBugScreen.kt
> +            coroutineScope.launch {
이런 뷰 관련 작업들은 Dispatchers.Main을 쓰는게 어떤가요?
근데 저걸 써서 진짜 도움이 되는지는 공부를 해봐야겠네요

2024-02-12 14:12 UTC, rladmsdh commented on feature/bug/src/main/java/team/retum/bug/ReportBugScreen.kt
> +            )
, 붙여주세요

2024-02-12 14:12 UTC, rladmsdh commented on feature/bug/src/main/java/team/retum/bug/ReportBugScreen.kt
> +                        onPressed = { pressed = it },
Implicit parameter 'it' of enclosing lambda is shadowed 이 경고 문구가 뜨는데 파라미터 이름을 설정해 주는게 좋을것 같아요

2024-02-12 23:59 UTC, parkuiery approved these changes

2024-02-13 00:18 UTC, parkuiery requested changes

2024-02-13 01:37 UTC, Tmdhoon2 commented on feature/bug/src/main/java/team/retum/bug/ReportBugScreen.kt
> +            coroutineScope.launch {
<img width="1378" alt="스크린샷 2024-02-13 오전 10 10 02" src="https://github.com/Team-return/JOBIS-ANDROID-V2/assets/102812085/583e4dd8-79d8-4ccf-ac0c-dd939d9762ef">

이게 저도 궁금해서 찾아봤는데 Dispatcher.Main을 전달하면 Dispatcher.Main에서 돌아가고 딱히 전달을 안하면 AndroidUiDispatcher라는 곳에서 돌아가더라구요

근데 AndroidUiDispatcher하고 Dispatcher.Main이 딱히 차이가 없다고 하네요 둘다 UI 작업하는 스레드라서

2024-02-13 01:58 UTC, parkuiery approved these changes

2024-02-13 02:37 UTC, rladmsdh approved these changes

2024-02-13 03:00 UTC, merged