🔗 :: (#55) 마이페이지 스크린 퍼블리싱
Team-return/JOBIS-ANDROID-V2 pull request #67
Opened 2024-02-15 01:43 UTC by diddbsgh

## 개요
마이페이지 스크린을 퍼블리싱 했습니다.

<img width="334" alt="image" src="https://github.com/Team-return/JOBIS-ANDROID-V2/assets/128462405/a33f6974-ea8e-4859-a65d-150c76a385e0">

### 작업 내용
- MyPageScreen 퍼블리싱

### 할 말
> 없음

2024-02-15 02:00 UTC, parkuiery commented on feature/mypage/src/main/java/team/returm/mypage/ui/MyPageScreen.kt
> +                    shape = RoundedCornerShape(12.dp)
,

2024-02-15 02:00 UTC, parkuiery commented on feature/mypage/src/main/java/team/returm/mypage/ui/MyPageScreen.kt
> +            horizontalArrangement = Arrangement.spacedBy(8.dp)
,

2024-02-15 02:00 UTC, parkuiery commented on feature/mypage/src/main/java/team/returm/mypage/ui/MyPageScreen.kt
> +                contentDescription = "meeting room icon"
,

2024-02-15 02:00 UTC, parkuiery commented on feature/mypage/src/main/java/team/returm/mypage/ui/MyPageScreen.kt
> +                verticalArrangement = Arrangement.spacedBy(4.dp)
,

2024-02-15 02:00 UTC, parkuiery commented on feature/mypage/src/main/java/team/returm/mypage/ui/MyPageScreen.kt
> +
공백 지워주세요

2024-02-15 02:01 UTC, parkuiery commented on feature/mypage/src/main/java/team/returm/mypage/ui/MyPageScreen.kt
> +        }
필요 없는 코드면 지워주세요

2024-02-15 02:01 UTC, parkuiery commented on feature/mypage/src/main/java/team/returm/mypage/ui/MyPageScreen.kt
> +    onItemClick: () -> Unit
,

2024-02-15 03:03 UTC, Tmdhoon2 requested changes

2024-02-15 03:03 UTC, Tmdhoon2 commented on feature/mypage/src/main/java/team/returm/mypage/ui/MyPageScreen.kt
> +            .clickable { onItemClick() },
```suggestion
            .clickable(
                enabled = true,
                onClick = onItemClick,
                onPressed = {},
            ),
```

2024-02-15 03:03 UTC, Tmdhoon2 commented on feature/mypage/src/main/java/team/returm/mypage/ui/MyPageScreen.kt
> +                .padding(end = 8.dp)
여기는 Row에다가 horizontalArrangement = Arrangement.spaceBy(8.dp) 주면 될 것 같아요

2024-02-15 03:03 UTC, Tmdhoon2 commented on feature/mypage/src/main/java/team/returm/mypage/ui/MyPageScreen.kt
> +)
여기는 이 파일에서만 쓰이는거면 private 붙여주세요

2024-02-15 03:03 UTC, Tmdhoon2 commented on feature/mypage/src/main/res/drawable/ic_bug_box.png
새로 추가하신 아이콘들 위에 코멘트대로 디자인 시스템 아이콘으로 바꾼후에 삭제해주세요!

2024-02-15 07:48 UTC, diddbsgh commented on feature/mypage/src/main/java/team/returm/mypage/ui/MyPageScreen.kt
> +    val (showWithdrawalModal, setShowWithdrawalModal) = remember { mutableStateOf(false) }
로그아웃이나 회원탈퇴 눌렀을때 모달 화면에 띄우거나 안보이게 하는 역할이요

2024-02-16 05:57 UTC, parkuiery approved these changes

2024-02-16 06:03 UTC, Tmdhoon2 approved these changes

2024-02-16 06:09 UTC, merged