🔗 :: (#56) 모집의로서 상세 퍼블리싱
Team-return/JOBIS-ANDROID-V2 pull request #68
Opened 2024-02-15 01:52 UTC by parkuiery

## 개요

<img width="365" alt="image" src="https://github.com/Team-return/JOBIS-ANDROID-V2/assets/128464859/8061459e-f1ac-4507-9f83-a02e7c476f9d">
<img width="371" alt="image" src="https://github.com/Team-return/JOBIS-ANDROID-V2/assets/128464859/8cb1e0b8-570a-4ea0-b5ed-2d9062380366">

모집의뢰서 상세 페이지 퍼블리싱 했습니다

### 작업 내용
- RecruitmentDetailScreen 퍼블리싱

### 할 말
> 북마크 아이콘이 찌그러지긴했는데 아마 디자인에서 사라질거같아요

2024-02-15 04:19 UTC, Tmdhoon2 requested changes

2024-02-15 04:19 UTC, Tmdhoon2 commented on feature/recruitment/src/main/java/team/retum/recruitment/ui/RecruitmentDetailScreen.kt
> +            modifier = Modifier.padding(start = 12.dp),
Row에다가 horizontalArrangement = Arrangement.spaceBy(12.dp) 주면 될 것 같아용

2024-02-15 04:19 UTC, Tmdhoon2 commented on feature/recruitment/src/main/java/team/retum/recruitment/ui/RecruitmentDetailScreen.kt
> +    Spacer(modifier = Modifier.height(12.dp))
Column으로 한 번 감싸고 Modifier.padding(vertical = 12.dp) 로 주는게 더 깔끔할 것 같아요

2024-02-15 04:19 UTC, Tmdhoon2 commented on feature/recruitment/src/main/java/team/retum/recruitment/ui/RecruitmentDetailScreen.kt
> +    Spacer(modifier = Modifier.height(12.dp))
여기도 위의 방식으로 패딩 주는게 더 깔끔할 것 같아요

2024-02-15 04:19 UTC, Tmdhoon2 commented on feature/recruitment/src/main/java/team/retum/recruitment/ui/RecruitmentDetailScreen.kt
> +                    .replace("]", "")
이거 자주 사용되는 것 같은데 확장함수로 빼두면 좋을 것 같아요

2024-02-15 04:19 UTC, Tmdhoon2 commented on feature/recruitment/src/main/java/team/retum/recruitment/ui/RecruitmentDetailScreen.kt
> +            Spacer(modifier = Modifier.weight(1f))
Row에다가 horizontalArrangement = Arrangement.SpaceBetween 주면 될 것 같아요

2024-02-15 04:19 UTC, Tmdhoon2 commented on feature/recruitment/src/main/java/team/retum/recruitment/ui/RecruitmentDetailScreen.kt
> +                else painterResource(id = R.drawable.ic_arrow_down),
```suggestion
                painter = painterResource(
                    id = if (showDetails) R.drawable.ic_arrow_up
                    else R.drawable.ic_arrow_down
                ),
```

2024-02-15 04:19 UTC, Tmdhoon2 commented on feature/recruitment/src/main/java/team/retum/recruitment/ui/RecruitmentDetailScreen.kt
> +            Column {
컬럼 꼭 필요한가요??

2024-02-15 04:36 UTC, parkuiery commented on app/src/main/java/team/retum/jobisandroidv2/navigation/MainNavigation.kt
> +        recruitmentDetail(onBackPressed = navController::navigateUp)
navigateUp은 앱을 종료하고 딥링크로 지정한 곳으로 이동하고
popBackStack은 백스텍에서 한단계 뒤로 돌아가고 없으면 아무것도 안하는데
navigateUp을 사용하라고 해서 navigateUp을 사용했습니다
그리고 뒤로가기 3번 연속으로 누르면 다 회원가입으로 넘어가는 버그가 있는거 같아요

2024-02-15 04:46 UTC, parkuiery commented on app/src/main/java/team/retum/jobisandroidv2/root/RootScreen.kt
저는 잘되는데 다시 한번 확인해주세요

2024-02-15 07:30 UTC, parkuiery commented on feature/recruitment/src/main/java/team/retum/recruitment/ui/RecruitmentDetailScreen.kt
> +            Column {
컬럼 없으면 합쳐져요

2024-02-19 03:35 UTC, Tmdhoon2 approved these changes

2024-02-19 13:19 UTC, diddbsgh approved these changes

2024-02-20 05:45 UTC, merged